name: CI

on:
  push:
    branches:
      - '*'
#    tags:
#      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Environment info
        run: |
          gradle --version

      - name: build
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v2
        with:
          name: openimis-claims-apk-${{github.run_number}}-${{github.sha}}
          path: ./claimManagement/build/outputs/**/*.apk

      - name: build
        run: |
          ./gradlew bundleDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v2
        with:
          name: openimis-claims-aab-${{github.run_number}}-${{github.sha}}
          path: ./claimManagement/build/outputs/**/*.aab
